version: '3.3'

services:
    post-crud-server:
        container_name: fastapi_server
        build: ./
        volumes:
            - ./:/usr/src/fastapi-post-crud
        working_dir: /usr/src/fastapi-post-crud
        command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "8000:8000"